language: erlang
before_install:
        - sudo apt-get install libpam0g-dev libexpat1-dev odbc-postgresql libmyodbc
        - if [ $PRESET = 'ldap_mnesia' ]; then sudo apt-get update && sudo apt-get install slapd ldap-utils; fi
        - tools/travis-generate-pass.sh
        - tools/travis-check-tests-branch.sh
install: tools/travis-build.sh
before_script:
        - tools/travis-setup-db.sh
        - if [ $PRESET = 'ldap_mnesia' ]; then tools/travis-setup-ldap.sh; fi
script: tools/travis-test.sh

after_script:
        - cat `ls -1 -d -t apps/ejabberd/logs/ct_run* | head -1`/apps.ejabberd.logs/run.*/suite.log
        - tail -100 dev/mongooseim_node1/log/ejabberd.log
        - if [ -s dev/mongooseim_node1/log/crash.log ]; then cat dev/mongooseim_node1/log/crash.log; fi
        - tail -100 dev/mongooseim_node2/log/ejabberd.log
        - if [ -s dev/mongooseim_node2/log/crash.log ]; then cat dev/mongooseim_node2/log/crash.log; fi
        - cat `ls -1 -d -t test/ejabberd_tests/ct_report/ct_run.* | head -1`/ejabberd_tests.*/run.*/suite.log
        - cat dev/mongooseim_node1/etc/ejabberd.cfg

after_success:
        - make cover_report

services: redis-server
branches:
        only:
                - master
notifications:
        email: linearregression@example.com
otp_release:
        - R16B01
        - R16B02
        - R16B03-1
        - R16B03
        - R16B
        - 17.0
        - 17.1
        - 17.3
        - 17.4

env:
        - PRESET=internal_redis DB=mnesia REL_CONFIG=with-redis
        - PRESET=internal_mnesia DB=mnesia
        - PRESET=mysql_mnesia DB=mysql REL_CONFIG=with-mysql
        - PRESET=odbc_pgsql_mnesia DB=pgsql REL_CONFIG=with-odbc
        - PRESET=pgsql_mnesia DB=pgsql REL_CONFIG=with-pgsql
        - PRESET=ldap_mnesia DB=mnesia
        - PRESET=external_mnesia DB=mnesia

matrix:
    fast_finish: true
    include:
        - otp_release: 17.0
          env: PRESET=internal_mnesia DB=mnesia
        - otp_release: R15B03
          env: PRESET=internal_mnesia DB=mnesia
        - otp_release: 17.4
          env: PRESET=internal_mnesia DB=mnesia

