language: erlang
before_install:
        - sudo apt-get install libpam0g-dev libexpat1-dev
        - if [ $TEST_CONFIG = 'ldap_mnesia' ]; then sudo apt-get install slapd ldap-utils; fi
        - tools/travis-generate-pass.sh
        - tools/travis-check-tests-branch.sh
install: tools/travis-build.sh
before_script:
        - tools/travis-setup-db.sh
        - if [ $TEST_CONFIG = 'ldap_mnesia' ]; then tools/travis-setup-ldap.sh; fi
script: tools/travis-test.sh

after_script:
        - cat `ls -1 -d -t apps/ejabberd/logs/ct_run* | head -1`/apps.ejabberd.logs/run.*/suite.log
        - tail -100 dev/mongooseim_node1/log/ejabberd.log
        - if [ -s dev/mongooseim_node1/log/crash.log ]; then cat dev/mongooseim_node1/log/crash.log; fi
        - cat `ls -1 -d -t test/ejabberd_tests/ct_report/ct_run.* | head -1`/ejabberd_tests.*/run.*/suite.log
        - cat dev/mongooseim_node1/etc/ejabberd.cfg
services: redis-server
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
otp_release:
        - R15B03
env:
        - TEST_CONFIG=internal_redis DB=mnesia
        - TEST_CONFIG=internal_mnesia DB=mnesia
        - TEST_CONFIG=odbc_redis DB=mysql
        - TEST_CONFIG=external_mnesia DB=mnesia
        - TEST_CONFIG=odbc_pgsql_mnesia DB=psql
        - TEST_CONFIG=ldap_mnesia DB=mnesia

